name: Docs

on:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install & build
        run: cd docs && yarn && yarn build

      - name: Deploy
        if: "contains('refs/heads/main', github.ref)"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
